### ISSUE TITLE
Question: Having Websocket for Separated Back-end & Front-end Projects

### ISSUE THREAD

**Issue by Steam1996** [jasrodis/spring-boot-vuejs-websockets#1]
Hi,

Thanks for the sample. Can we also use the Websocket feature if we run the VueJS app on different port? 

My front-end and back-end apps are different projects. They are not in one project. Can I use this implementation to send messages between back-end and front-end?

**Comment by jasrodis** [comment]
@Steam1996 In principle yes, the port is just a configuration

**Comment by jasrodis** [comment]
I mark this as close
